# 1. Usar la imagen oficial de .NET 9
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# 2. Copiar los archivos
COPY ["LamillaEscudero.Web/LamillaEscudero.Web.csproj", "LamillaEscudero.Web/"]
COPY ["LamillaEscudero.Application/LamillaEscudero.Application.csproj", "LamillaEscudero.Application/"]
COPY ["LamillaEscudero.Domain/LamillaEscudero.Domain.csproj", "LamillaEscudero.Domain/"]
COPY ["LamillaEscudero.Infrastructure/LamillaEscudero.Infrastructure.csproj", "LamillaEscudero.Infrastructure/"]

# 3. Restaurar dependencias de la WEB
RUN dotnet restore "LamillaEscudero.Web/LamillaEscudero.Web.csproj"

# 4. Copiar el resto del código y compilar
COPY . .
WORKDIR "/src/LamillaEscudero.Web"
RUN dotnet publish "LamillaEscudero.Web.csproj" -c Release -o /app/publish /p:UseAppHost=false

# 5. Configurar el servidor final de la página web
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
EXPOSE 8080
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "LamillaEscudero.Web.dll"]